config/routes.rb
Rails.application.routes.draw do
  resources :rentals

end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:name, :address, :property_type, :tenure, :size, :psf, :listingID, :price, :beds, :baths, :furnishing, :floor_level, :agent)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rentals/_form.html.erb
<%= form_for(@rental) do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :property_type %><br>
    <%= f.text_field :property_type %>
  </div>
  <div class="field">
    <%= f.label :tenure %><br>
    <%= f.text_field :tenure %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :psf %><br>
    <%= f.text_field :psf %>
  </div>
  <div class="field">
    <%= f.label :listingID %><br>
    <%= f.number_field :listingID %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :beds %><br>
    <%= f.text_field :beds %>
  </div>
  <div class="field">
    <%= f.label :baths %><br>
    <%= f.text_field :baths %>
  </div>
  <div class="field">
    <%= f.label :furnishing %><br>
    <%= f.text_field :furnishing %>
  </div>
  <div class="field">
    <%= f.label :floor_level %><br>
    <%= f.text_field :floor_level %>
  </div>
  <div class="field">
    <%= f.label :agent %><br>
    <%= f.text_field :agent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Property type</th>
      <th>Tenure</th>
      <th>Size</th>
      <th>Psf</th>
      <th>Listingid</th>
      <th>Price</th>
      <th>Beds</th>
      <th>Baths</th>
      <th>Furnishing</th>
      <th>Floor level</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.name %></td>
        <td><%= rental.address %></td>
        <td><%= rental.property_type %></td>
        <td><%= rental.tenure %></td>
        <td><%= rental.size %></td>
        <td><%= rental.psf %></td>
        <td><%= rental.listingID %></td>
        <td><%= rental.price %></td>
        <td><%= rental.beds %></td>
        <td><%= rental.baths %></td>
        <td><%= rental.furnishing %></td>
        <td><%= rental.floor_level %></td>
        <td><%= rental.agent %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form' %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rental.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @rental.address %>
</p>

<p>
  <strong>Property type:</strong>
  <%= @rental.property_type %>
</p>

<p>
  <strong>Tenure:</strong>
  <%= @rental.tenure %>
</p>

<p>
  <strong>Size:</strong>
  <%= @rental.size %>
</p>

<p>
  <strong>Psf:</strong>
  <%= @rental.psf %>
</p>

<p>
  <strong>Listingid:</strong>
  <%= @rental.listingID %>
</p>

<p>
  <strong>Price:</strong>
  <%= @rental.price %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @rental.beds %>
</p>

<p>
  <strong>Baths:</strong>
  <%= @rental.baths %>
</p>

<p>
  <strong>Furnishing:</strong>
  <%= @rental.furnishing %>
</p>

<p>
  <strong>Floor level:</strong>
  <%= @rental.floor_level %>
</p>

<p>
  <strong>Agent:</strong>
  <%= @rental.agent %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>